#include <stdio.h>
#include <iostream>
#include <string>
using std::cout;
using std::endl;
using std::string;
#ifdef _WIN32
	//define something for Windows (32-bit and 64-bit, this part is common)
	#ifdef _WIN64
		//define something for Windows (64-bit only)
		string const runsys = "win64";
	#else
		//define something for Windows (32-bit only)
	#endif
#elif __APPLE__
	#include "TargetConditionals.h"
	#if TARGET_IPHONE_SIMULATOR
		// iOS Simulator
	#elif TARGET_OS_IPHONE
		// iOS device
	#elif TARGET_OS_MAC
		// Other kinds of Mac OS
		string const runsys = "macos";
	#else
		#   error "Unknown Apple platform"
	#endif
#elif __linux__
	// linux
	string const runsys = "linux";
#elif __unix__ // all unices not caught above
	// Unix
	string const runsys = "unix";
#elif defined(_POSIX_VERSION)
	// POSIX
	string const runsys = "posix";
#else
	#error "Unknown compiler"
#endif

#include "makexxfile_embed.hpp"
#include "starter_embed.hpp"
#include <cstring>
//#include <atlib.hpp>
#include <cassert>

bool exists(char const *file) {
	FILE *fb = fopen(file, "r");
	if(fb == NULL) {
		return false;
	} else {
		fclose(fb);
		return true;
	}
}
void char2file(char const *file, const unsigned char *str, unsigned int len) {
	FILE *fb = fopen(file, "w");
	fwrite(str, len, sizeof(unsigned char), fb);
	fclose(fb);
}
void char2file(char const *file, const char *str, int len) {
	FILE *fb = fopen(file, "w");
	fwrite(str, len, sizeof(char), fb);
	fclose(fb);
}
#include <cstdio>
#include <memory>
#include <stdexcept>
#include <array>
#include "makexxfile.hpp"

std::string exec(char const *cmd) {
	std::array<char, 128> buffer;
	std::string result;
	std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd, "r"), pclose);
	if(!pipe) {
		throw std::runtime_error("popen() failed!");
	}
	while(fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr) {
		result += buffer.data();
	}
	return result;
}

char *atgrab_ascii_file(char const *file) {
	FILE *f = fopen(file, "r");
	fseek(f, 0, SEEK_END);
	long fsize = ftell(f);
	fseek(f, 0, SEEK_SET);  //same as rewind(f);
	char *string = (char *) malloc(fsize + 1);
	fread(string, fsize, 1, f);
	fclose(f);
	string[fsize] = 0;
	return string;
}

void run_cmd(string cmd) {
	//cout<<">cmd:"<<cmd<<endl;
	system(cmd.c_str());
	//cout<<">done"<<endl;
}

int main(int argc, char **argv) {
	//open atbuild.hpp first
	char const *hppmake = "makefile.hpp";
	char const *cppmake = "makefile.cpp";
	bool update_makefile_hpp = false;
	bool force_overwrite = false;
	bool compile_only = false;
	bool verbose = false;
	for(int i = 1; i < argc; i++) {
		if(strcmp(argv[i], "-u") == 0) {
			update_makefile_hpp = true;
		} else if(strcmp(argv[i], "-0") == 0) {
			verbose = true;
		} else if(strcmp(argv[i], "-f") == 0) {
			force_overwrite = true;
		} else if(strcmp(argv[i], "-c") == 0) {
			compile_only = true;
		}
	}
	if(!exists(hppmake) || update_makefile_hpp) {
		char2file(hppmake, makefile_hpp_content, sizeof(makefile_hpp_content) - 1);
		if(verbose)
			cout << "Generating makefile.hpp..." << endl;
		update_makefile_hpp = true;
	}
	if(!exists(cppmake)) {
		if(verbose)
			cout << "Generating " << cppmake << "." << endl;
		char2file(cppmake, makefile_example_content, sizeof(makefile_example_content) - 1);
	}
	vector<string> compilers = {"g++-8", "g++-7", "g++", "icpc"};
	int compiler_id = 0;
	if(verbose)
		cout << "SYSTEM:" << runsys << endl;
	bool is_windows = (runsys == "win64");
	if(is_windows) {
		run_cmd("del tmp_makexx.cpp tmp_makexx tmp_makexx.exe err_makexx.txt makefile_gen");
	} else {
		run_cmd("rm -f tmp_makexx.cpp tmp_makexx tmp_makexx.exe err_makexx.txt makefile_gen");
	}
	if(verbose)
		cout << "SEARCHING FOR A COMPILER:" << endl;
	//system("echo \"int main(){}\" >tmp.cpp");
	string small_prog = "int main(){}";
	char2file("tmp_makexx.cpp", small_prog.c_str(), small_prog.size());
	while(true) {
		run_cmd(compilers[compiler_id] + " -std=c++11 tmp_makexx.cpp -o tmp_makexx 2>err_makexx.txt");
		if(exists("tmp_makexx")) {
			break;
		} else if(exists("tmp_makexx.exe")) {
			break;
		} else {
			//cout << (compilers[compiler_id] ) << " didn't work trying something else!" << endl;
			compiler_id++;
			if(compiler_id >= compilers.size()) {
				std::cerr << "Coudn't find a C++ compiler!" << endl;
				return -1;
			}
		}
	}
	if(verbose)
		cout << (compilers[compiler_id]) << " is used." << endl;
	assert(compiler_id < compilers.size());
	run_cmd(compilers[compiler_id] + " -std=c++11 makefile.cpp -o makefile_gen");
	if(exists("makefile")) {
		auto a = atgrab_ascii_file("makefile");
		if(strncmp(a, makefile_header, strlen(makefile_header)) != 0) {
			//this means that the make file is not automatically generated
			if(!force_overwrite) {
				cout << "makefile is not updated becuase it is not generated by makexx" << endl;
				exit(-1);
			}
		}
		free(a);
	}
	//update the makefile
	if(verbose)
		cout << "Generating makefile.." << endl;
	if(!is_windows) {
		run_cmd("./makefile_gen");
	} else {
		run_cmd("makefile_gen.exe");
	}
	//run GNU make with the rest of parameters
	std::string a = "make " ;
	for(int i = 1; i < argc; i++) {
		if(strcmp(argv[i], "-u") == 0) {
		} else if(strcmp(argv[i], "-f") == 0) {
		} else {
			//pass the commandline arguments to make
			a += argv[i];
			a += " ";
		}
	}
	//exec(a.c_str());
	if(!compile_only)
		run_cmd(a);
	if(is_windows) {
		run_cmd("del tmp_makexx.cpp tmp_makexx tmp_makexx.exe err_makexx.txt makefile_gen");
	} else {
		run_cmd("rm -f tmp_makexx.cpp tmp_makexx tmp_makexx.exe err_makexx.txt makefile_gen");
	}
}
